// GENERATED FILE - DO NOT EDIT
//
// This file was generated by applying the following macros to the
// `example/freezed.gen.dart` file:
//
//
// To make changes you should edit the `example/freezed.gen.dart` file;

import 'macros/freezed.dart';

@freezed
class FreezedUnion {
  FreezedUnion();
  factory FreezedUnion.data(DateTime time, {required String info}) =
      FreezedData;
  factory FreezedUnion.error(String error) = FreezedError;
  factory FreezedUnion.loading(Duration time) = FreezedLoading;
}
